services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672"  
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  fastapi:
    build: .
    container_name: fastapi_mensageria
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=mensagens
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    build: .
    container_name: consumer_app
    command: ["python", "-u", "app/consumer.py"]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=mensagens
    depends_on:
      rabbitmq:
        condition: service_healthy